apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-func
spec:
  selector:
    matchLabels:
      app: hello-func
  template:
    metadata:
      labels:
        app: hello-func
    spec:
      containers:
      - name: hello-func
        image: anbossar.azurecr.io/prom-func-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-func-svc
  labels:
    app: hello-func
spec:
  selector:
    app: hello-func
  type: LoadBalancer
  ports:
  - name: web
    port: 8088
    targetPort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-func
  labels:
    team: frontend
    release: prometheus
spec:
  endpoints:
  - path: /api/metrics
    port: web
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: hello-func